### ISSUE TITLE
'!=' and '==' converted to '! =' and '= ='

### ISSUE THREAD

**Issue by hypermurea** [cosmicexplorer/format-c#1]
the extra spaces make the syntax invalid

**Comment by cosmicexplorer** [comment]
Thanks! See the fix [here](https://github.com/cosmicexplorer/c-format-stream/blob/2d1628f2c87ff7430a4a6a7d8c07d14b26fbde4f/src/c-format-stream.coffee#L158). Not 100% sure why I didn't realize that wasn't added to my test case before, but it's fixed now.

**Comment by cosmicexplorer** [comment]
Just saying again so it's clear, this was a super super helpful comment about something that I could literally have never noticed, I really appreciate it!!
